# 本地构建镜像，使用本地构建的base镜像
# 使用方法：docker build -t xiaozhi-esp32-server:server_latest -f ./Dockerfile-server-local .
FROM xiaozhi-esp32-server:server-base

COPY main/xiaozhi-server .

# 启动应用
CMD ["python", "app.py"]








